### ISSUE TITLE
A couple of documentation mistakes

### ISSUE THREAD

**Issue by courtarro** [mikenye/docker-adsb-to-influxdb#12]
> By default, when Telegraf creates a database, it uses the default retention policy. At the time of writing, with InfluxDB version 1.7, this means the data is kept for 7 days (168 hours).

The default retention policy of InfluxDB is `0s`, or forever. I believe you're mixing up the overall retention policy with the shard retention policy, which is 7 days. Referring to your second example:

```
InfluxDB shell version: 1.8.0
> CREATE RETENTION POLICY "30_days" ON "adsb" DURATION 30d REPLICATION 1 DEFAULT
> use adsb
Using database adsb
> show retention policies
name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
autogen 0s       168h0m0s           1        false
30_days 720h0m0s 24h0m0s            1        true
```

... the `autogen` retention policy is forever, with 7-day shards, whereas the `30_days` policy is actually 30 days, with a 1-day shard. (Note the `duration` column.)

Another minor mistake is that you've referred to `INFLUXDB_URL` instead of `INFLUXDBURL` in one spot.

**Comment by mikenye** [comment]
Apologies for the errors, thanks for bringing them to my attention. I've just updated the readme.
