### ISSUE TITLE
readsb heavy writes

### ISSUE THREAD

**Issue by ionigman** [mikenye/docker-adsb-to-influxdb#13]
readsb performs some pretty heavy writes on its local JSONs. 

It may be advantageous for folks to set the /run/readsb to tmpfs either in their docker run command, or their docker-compose file. 

I was seeing a significant increase in write load on my docker host once I started the container and determined that it was readsb.
Setting the directory to a tmpfs mount stopped the writes and things are working normally. 

This will really only be of concern long-term with SSD drives on docker hosts.

**Comment by mikenye** [comment]
Hi @ionigman, this is a great suggestion. I've updated the readme in #14. Thanks.
