### ISSUE TITLE
LATEST tag fails to load

### ISSUE THREAD

**Issue by kyleinprogress** [mikenye/docker-adsb-to-influxdb#3]
Just a heads up, but if you try and use this and don't specify `:development`, it will fail.

Using `mikenye/adsb-to-influxdb:latest`, you get the following error:
```
Pulling adsb2influxdb (mikenye/adsb-to-influxdb:latest)...
ERROR: manifest for mikenye/adsb-to-influxdb:latest not found: manifest unknown: manifest unknown
```

It appears there's no `latest` build in [docker-hub](https://hub.docker.com/r/mikenye/adsb-to-influxdb/builds), so I'm guessing that's what the actual issue is.

**Comment by mikenye** [comment]
Hi @kyleinprogress, thanks for the heads-up. I’m actually aware of this - I haven’t put the build script together yet as this is a relatively new image and I’ve had some issues with my build farm. Everything should be back to normal in the next few hours, I’ll let you know when the `latest` image is up. Thanks!

**Comment by mikenye** [comment]
Hi @kyleinprogress, automated builds are now happening nightly. The `latest` version of the image is now available. Thanks!
